#!/bin/bash

if [[ "$1" == "-h" ]] || [[ -z "$1" ]]; then
	echo "Script to compile and execute assembly code for labs.\
    ARG1   lab dir. Must contain lab.s file to compile"
fi

# find dirname of script, used for portability
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# find full path of arg1
ARG1=$(readlink -f $1)

# if arg2 present, build different executible than "lab"
if [[ -z "$2" ]]; then
	LAB_NAME=lab
else
	LAB_NAME=$2
fi

MAKEFILE="make -C ${ARG1} -f ${DIR}/Makefile lab=${LAB_NAME}"
$MAKEFILE clean
$MAKEFILE

# execute & direct output to file
${ARG1}/${LAB_NAME} 2>&1 | tee ${ARG1}/${LAB_NAME}_output.txt
