#!/bin/bash

if [[ "$1" == "-h" ]] || [[ -z "$1" ]]; then
	echo "Script to compile and execute assembly code for labs.\
    ARG1   lab dir. Must contain lab.s file to compile"
fi

# find dirname of script, used for portability
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# find full path of arg1
ARG1=$(readlink -f $1)

# use standardized makefile + arg1 for dir
MAKEFILE="make -C ${ARG1} -f ${DIR}/Makefile"
$MAKEFILE clean
$MAKEFILE

#print output of lab
printf "\nOUTPUT:\n"
${ARG1}/lab ; echo $?
